[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "ApparatusFix"
description = "A Lethal Company mod that fixes Apparatus sound desyncs."
websiteUrl = "https://github.com/AndreyMrovol/LethalApparatusFix/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../ApparatusFix/dist"

[[build.copy]]
source = "../ApparatusFix/bin/Release/netstandard2.1/ApparatusFix.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]